name: example-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.16.2
  - matplotlib=3.2.2
  - pandas
  - ipywidgets
  - traitlets
  - bqplot=0.12.30
  - plolty=3.7.0
  - pillow=5.4.1
  - pip=19.0
  - scikit-learn=0.20.3
  
